// Local mocked browser only. Every external request is blocked.
import {chromium} from './.vercel/phase4e1-browser-tools/node_modules/playwright/index.mjs';
import {createServer} from 'node:http';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const mock=`window.calls=[];window.reads=0;window.fail=false;
window.services=[{id:'s',vendor_id:'v',campus_id:'c',category_id:'root',subcategory_id:'sub',name:'<img src=x onerror=alert(1)>',description:'Keep',price_type:'QUOTE',starting_price_kobo:125050,image_url:null,turnaround_time:'Day',is_active:false,requires_file_upload:false,requires_appointment:false}, {id:'legacy',vendor_id:'v',campus_id:'c',category_id:'food',subcategory_id:'sub',name:'Legacy',description:null,price_type:'FIXED',starting_price_kobo:100,is_active:true}];
const data={vendors:[{id:'v',name:'Vendor',status:'ACTIVE',is_verified:true}],campuses:[{id:'c',name:'Campus',is_active:true}],categories:[{id:'root',name:'Services',slug:'services',parent_id:null,is_active:true},{id:'sub',name:'Printing',parent_id:'root',is_active:true},{id:'food',name:'Food',slug:'food',parent_id:null,is_active:true}],vendor_campuses:[{vendor_id:'v',campus_id:'c',is_active:true}]};
export const getSupabaseClient=()=>({from(table){return {select(){window.reads++;return Promise.resolve({data:table==='services'?structuredClone(window.services):data[table],error:null})}}},async rpc(name,args){window.calls.push({name,args});if(window.fail)return {error:{message:'unsafe <script>details</script>'}};let s;if(name==='admin_update_service'){s=window.services.find(s=>s.id===args.p_service_id);Object.assign(s,args.p_patch);}else{s={id:'new',...Object.fromEntries(Object.entries(args).map(([k,v])=>[k.slice(2),v]))};window.services.push(s);}return {data:structuredClone(s)}}});`;
const server=createServer((req,res)=>{res.setHeader('Content-Type',req.url.endsWith('.js')?'text/javascript':'text/html');if(req.url==='/js/supabase.js')return res.end(mock);if(req.url==='/js/admin-services.js')return res.end(readFileSync(new URL('./js/admin-services.js',import.meta.url)));res.end('<div id="root"></div><script type="module">import {createAdminServices} from "/js/admin-services.js"; window.ui=createAdminServices(document.querySelector("#root"));await window.ui.init();</script>');});
await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser,passed=0;
async function test(n,f){await f();passed++;console.log('PASS: '+n);}
try{
 browser=await chromium.launch({headless:true,executablePath:'C:/Users/hp/AppData/Local/ms-playwright/chromium-1228/chrome-win64/chrome.exe'});
 const page=await browser.newPage();await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());page.on('dialog',d=>d.accept());
 await page.goto('http://127.0.0.1:'+server.address().port);await page.locator('#as-list table').waitFor();
 await test('list safe rendering and no mutation on load',async()=>{assert.equal(await page.locator('#as-list img').count(),0);assert.equal(await page.evaluate(()=>window.calls.length),0);assert((await page.locator('#as-list').innerText()).includes('<img'));});
 await test('no Delete control',async()=>assert.equal(await page.getByRole('button',{name:/delete/i}).count(),0));
 await test('filters/search do not mutate',async()=>{await page.fill('#as-filter-search','Legacy');assert.equal(await page.getByRole('button',{name:'Edit Service',exact:true}).count(),1);await page.fill('#as-filter-search','');await page.selectOption('#as-filter-availability','false');assert.equal(await page.getByRole('button',{name:'Edit Service',exact:true}).count(),1);await page.selectOption('#as-filter-availability','');assert.equal(await page.evaluate(()=>window.calls.length),0);});
 await test('add defaults unpublished and eligible category dependent child',async()=>{await page.click('#as-add');assert.equal(await page.isChecked('#as-is_active'),false);await page.selectOption('#as-vendor_id','v');await page.selectOption('#as-campus_id','c');assert.equal(await page.inputValue('#as-category_id'),'root');assert.equal(await page.locator('#as-subcategory_id option').count(),2);});
 await test('FIXED requires exact price and rejects decimals beyond two',async()=>{await page.selectOption('#as-price_type','FIXED');await page.fill('#as-name','New Service');await page.click('#as-save');assert.equal(await page.evaluate(()=>window.calls.length),0);await page.fill('#as-starting_price_kobo','1.001');await page.click('#as-save');assert.equal(await page.evaluate(()=>window.calls.length),0);});
 await test('failed create preserves form and sanitizes server error',async()=>{await page.fill('#as-starting_price_kobo','1250.50');await page.evaluate(()=>window.fail=true);await page.click('#as-save');await page.locator('#as-error').filter({hasText:'Unable to save'}).waitFor();assert.equal(await page.inputValue('#as-name'),'New Service');assert.equal(await page.locator('#as-dialog').evaluate(e=>e.open),true);assert(!(await page.locator('#as-error').innerText()).includes('unsafe'));});
 await test('create only RPC, exact kobo and authoritative refresh',async()=>{await page.evaluate(()=>window.fail=false);const reads=await page.evaluate(()=>window.reads);await page.click('#as-save');await page.waitForFunction(()=>!document.querySelector('#as-dialog').open);const call=await page.evaluate(()=>window.calls.at(-1));assert.equal(call.name,'admin_create_service');assert.equal(call.args.p_starting_price_kobo,125050);assert.equal(call.args.p_is_active,false);assert((await page.evaluate(()=>window.reads))>reads);});
 await page.getByRole('button',{name:'Edit Service',exact:true}).first().click();
 await test('edit immutable vendor and campus; no provider field',async()=>{assert(await page.isDisabled('#as-vendor_id'));assert(await page.isDisabled('#as-campus_id'));assert.equal(await page.locator('#as-provider_user_id').count(),0);});
 await test('failed update preserves values',async()=>{await page.fill('#as-description','Changed');await page.evaluate(()=>window.fail=true);await page.click('#as-save');await page.locator('#as-error').filter({hasText:'Unable to save'}).waitFor();assert.equal(await page.inputValue('#as-description'),'Changed');await page.evaluate(()=>window.fail=false);});
 await test('explicit null clears only touched field',async()=>{await page.fill('#as-description','');await page.click('#as-save');await page.waitForFunction(()=>!document.querySelector('#as-dialog').open);const call=await page.evaluate(()=>window.calls.at(-1));assert.equal(call.name,'admin_update_service');assert.deepEqual(call.args.p_patch,{description:null});});
 await test('QUOTE blank price accepted and explicit NULL sent',async()=>{await page.getByRole('button',{name:'Edit Service',exact:true}).first().click();await page.fill('#as-starting_price_kobo','');await page.click('#as-save');await page.waitForFunction(()=>!document.querySelector('#as-dialog').open);assert.deepEqual(await page.evaluate(()=>window.calls.at(-1).args.p_patch),{starting_price_kobo:null});});
 await test('legacy warning and isolated quarantine action',async()=>{assert((await page.locator('#as-list').innerText()).includes('Legacy/context issue'));await page.getByRole('button',{name:'Make unavailable',exact:true}).click();await page.waitForFunction(()=>window.services.find(s=>s.id==='legacy').is_active===false);assert.deepEqual(await page.evaluate(()=>window.calls.at(-1).args.p_patch),{is_active:false});});
 await test('legacy invalid publish disabled',async()=>{const row=page.locator('tr').filter({hasText:'Legacy'});assert(await row.getByRole('button',{name:'Publish service'}).isDisabled());});
 await test('reset removes data and closes form',async()=>{await page.evaluate(()=>window.ui.reset());assert.equal(await page.locator('#as-list table').count(),0);});
 console.log(`SERVICE BROWSER: ${passed}/${passed} PASS`);
}finally{await browser?.close();await new Promise(r=>server.close(r));}
