create table public.services (
  id uuid primary key default gen_random_uuid(),
  legacy_key text unique,
  slug text not null,
  provider_user_id uuid not null references public.profiles(id) on delete restrict,
  vendor_id uuid references public.vendors(id) on delete restrict,
  campus_id uuid not null references public.campuses(id) on delete restrict,
  category_id uuid not null references public.categories(id) on delete restrict,
  subcategory_id uuid references public.categories(id) on delete restrict,
  name text not null,
  description text,
  starting_price_kobo bigint check (starting_price_kobo is null or starting_price_kobo >= 0),
  price_type public.price_type not null default 'QUOTE',
  image_url text,
  turnaround_time text,
  requires_file_upload boolean not null default false,
  requires_appointment boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider_user_id, campus_id, slug),
  unique (provider_user_id, campus_id, name),
  foreign key (vendor_id, campus_id) references public.vendor_campuses(vendor_id, campus_id) on delete restrict
);

create table public.service_requests (
  id uuid primary key default gen_random_uuid(),
  service_id uuid not null references public.services(id) on delete restrict,
  requester_user_id uuid not null references public.profiles(id) on delete restrict,
  provider_user_id uuid not null references public.profiles(id) on delete restrict,
  vendor_id uuid references public.vendors(id) on delete restrict,
  campus_id uuid not null references public.campuses(id) on delete restrict,
  delivery_type public.service_delivery_type not null,
  customer_location text,
  description text not null,
  file_url text,
  estimated_budget_kobo bigint check (estimated_budget_kobo is null or estimated_budget_kobo >= 0),
  preferred_date date,
  preferred_time time,
  status public.service_request_status not null default 'SUBMITTED',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  check (completed_at is null or status = 'COMPLETED')
);
