/**
 * Campus Life Express (CLX 2.0) - Authoritative Data Architecture
 * Flagship Product of Dandalin Sauki Ltd
 */

export const CLX_CONFIG = {
    brandName: "Campus Life Express",
    shortName: "CLX",
    company: "Dandalin Sauki Ltd",
    version: "2.0.0",
    defaultCampus: "unimaid",
    currency: "₦",
    tagline: "Everything you need around campus, in one place.",
    supportPhone: "+234 915 073 6638",
    supportEmail: "support@campuslifeexpress.com",
    whatsappNumber: "2349150736638"
};

export const CAMPUSES = [
    {
        id: "unimaid",
        name: "University of Maiduguri",
        shortName: "UNIMAID",
        location: "Maiduguri, Borno State",
        deliveryZones: ["Acada Complex", "Hostel A-D", "Hostel E-H", "Science Complex", "Faculty of Law", "Staff Quarters", "Commercial Center"],
        active: true
    },
    {
        id: "kiu",
        name: "Kashim Ibrahim University",
        shortName: "KIU",
        location: "Maiduguri, Borno State",
        deliveryZones: ["Main Campus", "Student Village", "Admin Block", "Library Area", "Sports Complex"],
        active: true
    },
    {
        id: "buk",
        name: "Bayero University Kano",
        shortName: "BUK",
        location: "Kano, Kano State",
        deliveryZones: ["New Site", "Old Site", "Hostels"],
        active: true
    }
];

export const CATEGORIES = [
    {
        id: "food",
        name: "Food",
        slug: "food",
        icon: "fa-utensils",
        badge: "Restaurants & Vendors",
        description: "Campus restaurants, food vendors, quick snacks, and refreshing drinks for everyone on campus.",
        subcategories: ["Restaurants", "Campus Food Vendors", "Snacks", "Drinks"],
        image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop&q=80",
        path: "/food"
    },
    {
        id: "shopping",
        name: "Shopping",
        slug: "shopping",
        icon: "fa-bag-shopping",
        badge: "Fashion, Tech & Essentials",
        description: "Fashion, footwear, phone accessories, beauty products, books, and campus stationery for students, staff, and visitors.",
        subcategories: ["Fashion", "Shoes", "Phones & Accessories", "Beauty", "Books", "Stationery"],
        image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600&auto=format&fit=crop&q=80",
        path: "/shopping"
    },
    {
        id: "services",
        name: "Campus Services",
        slug: "services",
        icon: "fa-screwdriver-wrench",
        badge: "Trusted Service Providers",
        description: "Printing, document binding, graphics design, laundry, barbing, tailoring, and phone repairs.",
        subcategories: ["Printing", "Graphics", "Photography", "Laundry", "Barbing", "Tailoring", "Phone Repair"],
        image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&auto=format&fit=crop&q=80",
        path: "/services"
    },
    {
        id: "marketplace",
        name: "Student Marketplace",
        slug: "marketplace",
        icon: "fa-handshake",
        badge: "Student-to-Student",
        description: "Buy and sell used textbooks, electronics, room furniture, and hostel items directly with students.",
        subcategories: ["Used Textbooks", "Used Electronics", "Furniture", "Hostel Items", "Student-to-Student Sales"],
        image: "https://images.unsplash.com/photo-1534452203293-494d7ddbf7e0?w=600&auto=format&fit=crop&q=80",
        path: "/marketplace"
    },
    {
        id: "delivery",
        name: "Delivery & Errands",
        slug: "delivery",
        icon: "fa-truck-fast",
        badge: "Fast Campus Dispatch",
        description: "Campus parcel delivery, vendor order collection, and reliable errand assistance for the campus community.",
        subcategories: ["Campus Delivery", "Vendor Pickup", "Errands"],
        image: "https://images.unsplash.com/photo-1617347454431-f49d7ff5c3b1?w=600&auto=format&fit=crop&q=80",
        path: "/delivery"
    }
];

export const VENDORS = [
    {
        id: "v-safari-delight",
        name: "Safari Delight Kitchen",
        category: "food",
        subcategories: ["Restaurants", "Campus Food Vendors"],
        campus: "unimaid",
        location: "Commercial Center, Block B, Shop 14",
        hours: "08:00 AM - 08:30 PM",
        rating: 4.8,
        reviewCount: 94,
        verified: true,
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&auto=format&fit=crop&q=80",
        description: "Specializes in traditional Jollof rice, fried rice, tender beef, and grilled chicken for campus customers.",
        phone: "+234 803 123 4567"
    },
    {
        id: "v-bukhari-grill",
        name: "Al-Bukhari Suya & Shawarma",
        category: "food",
        subcategories: ["Snacks", "Restaurants"],
        campus: "unimaid",
        location: "Opposite Complex Hall, Main Gate Area",
        hours: "03:00 PM - 10:00 PM",
        rating: 4.9,
        reviewCount: 120,
        verified: true,
        image: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=600&auto=format&fit=crop&q=80",
        description: "Freshly made beef and chicken Shawarma, spiced Suya skewers, and cold chilled drinks.",
        phone: "+234 802 987 6543"
    },
    {
        id: "v-chill-sip",
        name: "Chill & Sip Refreshments",
        category: "food",
        subcategories: ["Drinks", "Snacks"],
        campus: "unimaid",
        location: "Near Science Lecture Theatre",
        hours: "09:00 AM - 06:00 PM",
        rating: 4.7,
        reviewCount: 45,
        verified: true,
        image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80",
        description: "Fresh fruit juices, boba, iced zobo, yoghurt smoothies, and meat pies.",
        phone: "+234 806 333 4455"
    },
    {
        id: "v-campus-threads",
        name: "Campus Threads & Kicks",
        category: "shopping",
        subcategories: ["Fashion", "Shoes"],
        campus: "unimaid",
        location: "Shopping Complex, Wing C",
        hours: "09:00 AM - 07:00 PM",
        rating: 4.8,
        reviewCount: 62,
        verified: true,
        image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600&auto=format&fit=crop&q=80",
        description: "Affordable streetwear, unisex sneakers, canvas shoes, tote bags, and plain tees for campus customers.",
        phone: "+234 805 444 8899"
    },
    {
        id: "v-gadget-hub",
        name: "Apex Gadget Hub",
        category: "shopping",
        subcategories: ["Phones & Accessories"],
        campus: "unimaid",
        location: "Hostel D Annex Plaza",
        hours: "08:30 AM - 08:00 PM",
        rating: 4.9,
        reviewCount: 88,
        verified: true,
        image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600&auto=format&fit=crop&q=80",
        description: "Fast charging cables, power banks, Bluetooth earbuds, OTG drives, and screen protectors.",
        phone: "+234 818 222 1100"
    },
    {
        id: "v-scholar-store",
        name: "Scholar Book & Stationery Mart",
        category: "shopping",
        subcategories: ["Books", "Stationery"],
        campus: "unimaid",
        location: "Faculty of Arts Walkway",
        hours: "08:00 AM - 06:00 PM",
        rating: 4.6,
        reviewCount: 39,
        verified: true,
        image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600&auto=format&fit=crop&q=80",
        description: "Lecture notebooks, engineering calculators, drawing pads, staplers, and textbooks.",
        phone: "+234 807 555 7722"
    },
    {
        id: "v-quickprint-press",
        name: "QuickPrint & Cyber Hub",
        category: "services",
        subcategories: ["Printing", "Graphics"],
        campus: "unimaid",
        location: "Library Basement & Complex Wing",
        hours: "07:30 AM - 08:00 PM",
        rating: 4.9,
        reviewCount: 142,
        verified: true,
        image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=600&auto=format&fit=crop&q=80",
        description: "High-speed document printing, project hardcover binding, poster design, and passport photos.",
        phone: "+234 803 777 9911"
    },
    {
        id: "v-fresh-laundry",
        name: "FreshWash Campus Laundry",
        category: "services",
        subcategories: ["Laundry"],
        campus: "unimaid",
        location: "Hostel B Common Ground",
        hours: "07:00 AM - 07:00 PM",
        rating: 4.7,
        reviewCount: 56,
        verified: true,
        image: "https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?w=600&auto=format&fit=crop&q=80",
        description: "Wash, dry, press, and fold laundry services with same-day hostel pickup and delivery.",
        phone: "+234 802 111 6633"
    },
    {
        id: "v-royale-cuts",
        name: "Royale Unisex Cuts & Salon",
        category: "services",
        subcategories: ["Barbing"],
        campus: "unimaid",
        location: "Student Union Building Ground Floor",
        hours: "09:00 AM - 09:00 PM",
        rating: 4.8,
        reviewCount: 78,
        verified: true,
        image: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=600&auto=format&fit=crop&q=80",
        description: "Haircuts, beard grooming, washing, hair styling, and relaxing campus atmosphere.",
        phone: "+234 814 666 3322"
    },
    {
        id: "v-ifix-repairs",
        name: "iFix Tech & Phone Repairs",
        category: "services",
        subcategories: ["Phone Repair"],
        campus: "unimaid",
        location: "Engineering Quad, Kiosk 4",
        hours: "09:00 AM - 06:30 PM",
        rating: 4.8,
        reviewCount: 83,
        verified: true,
        image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80",
        description: "Screen replacement, battery upgrades, charging port fixing, and software flashing.",
        phone: "+234 809 888 1234"
    }
];

export const PRODUCTS = [
    // --- FOOD PRODUCTS ---
    {
        id: "p-jollof-chicken",
        name: "Special Jollof Rice & Crispy Chicken",
        category: "food",
        subcategory: "Restaurants",
        price: 2200,
        vendorId: "v-safari-delight",
        vendorName: "Safari Delight Kitchen",
        campus: "unimaid",
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80",
        description: "Smoky seasoned Nigerian party Jollof rice served with spiced grilled chicken and fried plantain.",
        rating: 4.9,
        isPopular: true,
        inStock: true
    },
    {
        id: "p-fried-rice-beef",
        name: "Special Fried Rice & Peppered Beef",
        category: "food",
        subcategory: "Restaurants",
        price: 2000,
        vendorId: "v-safari-delight",
        vendorName: "Safari Delight Kitchen",
        campus: "unimaid",
        image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&auto=format&fit=crop&q=80",
        description: "Stir-fried vegetable rice garnished with liver cubes and served with soft peppered beef.",
        rating: 4.7,
        isPopular: true,
        inStock: true
    },
    {
        id: "p-shawarma-double",
        name: "Double Sausage Beef Shawarma",
        category: "food",
        subcategory: "Snacks",
        price: 1800,
        vendorId: "v-bukhari-grill",
        vendorName: "Al-Bukhari Suya & Shawarma",
        campus: "unimaid",
        image: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=600&auto=format&fit=crop&q=80",
        description: "Toasted pita wrap packed with spiced grilled beef, 2 sausages, crunchy cabbage, and creamy sauce.",
        rating: 4.9,
        isPopular: true,
        inStock: true
    },
    {
        id: "p-suya-skewer-pack",
        name: "Special Beef Suya Pack",
        category: "food",
        subcategory: "Snacks",
        price: 1500,
        vendorId: "v-bukhari-grill",
        vendorName: "Al-Bukhari Suya & Shawarma",
        campus: "unimaid",
        image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&auto=format&fit=crop&q=80",
        description: "Grilled beef suya coated in Yaji spice with sliced onions and fresh cucumber.",
        rating: 4.8,
        isPopular: false,
        inStock: true
    },
    {
        id: "p-zobo-fresh",
        name: "Chilled Ginger Hibiscus (Zobo) 500ml",
        category: "food",
        subcategory: "Drinks",
        price: 500,
        vendorId: "v-chill-sip",
        vendorName: "Chill & Sip Refreshments",
        campus: "unimaid",
        image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80",
        description: "Natural hibiscus flower drink brewed with fresh ginger, pineapple chunks, and cloves.",
        rating: 4.8,
        isPopular: true,
        inStock: true
    },
    {
        id: "p-meatpie-snack",
        name: "Golden Flaky Beef Meat Pie",
        category: "food",
        subcategory: "Snacks",
        price: 700,
        vendorId: "v-chill-sip",
        vendorName: "Chill & Sip Refreshments",
        campus: "unimaid",
        image: "https://images.unsplash.com/photo-1621236378699-8597fee6a1ce?w=600&auto=format&fit=crop&q=80",
        description: "Rich buttery shortcrust pastry filled with minced beef, potatoes, and mild carrots.",
        rating: 4.6,
        isPopular: false,
        inStock: true
    },

    // --- STUDENT SHOPPING PRODUCTS ---
    {
        id: "p-powerbank-20k",
        name: "20,000mAh Fast Charging Power Bank",
        category: "shopping",
        subcategory: "Phones & Accessories",
        price: 14500,
        vendorId: "v-gadget-hub",
        vendorName: "Apex Gadget Hub",
        campus: "unimaid",
        image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600&auto=format&fit=crop&q=80",
        description: "Dual USB + Type-C 22.5W fast charging power bank with digital LED battery display.",
        rating: 4.9,
        isPopular: true,
        inStock: true
    },
    {
        id: "p-earbuds-tws",
        name: "Wireless TWS Earbuds (Noise Cancelling)",
        category: "shopping",
        subcategory: "Phones & Accessories",
        price: 8500,
        vendorId: "v-gadget-hub",
        vendorName: "Apex Gadget Hub",
        campus: "unimaid",
        image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80",
        description: "Crystal-clear bass, 24-hour total playtime with charging case, and touch controls.",
        rating: 4.7,
        isPopular: true,
        inStock: true
    },
    {
        id: "p-sneakers-white",
        name: "Classic White Low-Top Campus Sneakers",
        category: "shopping",
        subcategory: "Shoes",
        price: 12000,
        vendorId: "v-campus-threads",
        vendorName: "Campus Threads & Kicks",
        campus: "unimaid",
        image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&auto=format&fit=crop&q=80",
        description: "Comfortable durable rubber sole sneakers suitable for daily lectures and casual walks.",
        rating: 4.8,
        isPopular: true,
        inStock: true
    },
    {
        id: "p-tote-canvas",
        name: "Minimalist Heavyweight Canvas Tote Bag",
        category: "shopping",
        subcategory: "Fashion",
        price: 4500,
        vendorId: "v-campus-threads",
        vendorName: "Campus Threads & Kicks",
        campus: "unimaid",
        image: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop&q=80",
        description: "Reinforced straps with zipper compartment, fits 15-inch laptops and large textbooks.",
        rating: 4.8,
        isPopular: false,
        inStock: true
    },
    {
        id: "p-calc-fx991",
        name: "Scientific Calculator FX-991EX Plus",
        category: "shopping",
        subcategory: "Stationery",
        price: 9500,
        vendorId: "v-scholar-store",
        vendorName: "Scholar Book & Stationery Mart",
        campus: "unimaid",
        image: "https://images.unsplash.com/photo-1587145820266-a5951ee6f620?w=600&auto=format&fit=crop&q=80",
        description: "Natural textbook display, 552 functions, dual solar and battery power for STEM students.",
        rating: 4.9,
        isPopular: true,
        inStock: true
    },
    {
        id: "p-notebook-pack",
        name: "Hardcover Ruled Lecture Notebook (Pack of 3)",
        category: "shopping",
        subcategory: "Stationery",
        price: 3200,
        vendorId: "v-scholar-store",
        vendorName: "Scholar Book & Stationery Mart",
        campus: "unimaid",
        image: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=600&auto=format&fit=crop&q=80",
        description: "200-page 80gsm premium smooth white paper notebooks with sturdy moisture-resistant covers.",
        rating: 4.6,
        isPopular: false,
        inStock: true
    }
];

export const SERVICES = [
    {
        id: "s-project-printing",
        name: "Document & Final Project Hardcover Binding",
        category: "services",
        subcategory: "Printing",
        startingPrice: 300,
        priceType: "starting_from",
        priceLabel: "From ₦300 / copy",
        providerId: "v-quickprint-press",
        providerName: "QuickPrint & Cyber Hub",
        campus: "unimaid",
        turnaround: "1 - 3 Hours",
        image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=600&auto=format&fit=crop&q=80",
        description: "High-speed laser printing, colour graphics pages, and accredited university-standard golden embossed hardcover binding.",
        requiresFileUpload: true,
        requiresInstructions: true,
        rating: 4.9
    },
    {
        id: "s-graphic-design",
        name: "Banner, Flyer & Student Event Graphics",
        category: "services",
        subcategory: "Graphics",
        startingPrice: 4000,
        priceType: "fixed",
        priceLabel: "₦4,000 fixed",
        providerId: "v-quickprint-press",
        providerName: "QuickPrint & Cyber Hub",
        campus: "unimaid",
        turnaround: "Same Day (4 - 6 Hours)",
        image: "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=600&auto=format&fit=crop&q=80",
        description: "Professional digital posters, social media banners, association campaign flyers, and branding assets.",
        requiresFileUpload: false,
        requiresInstructions: true,
        rating: 4.8
    },
    {
        id: "s-laundry-bag",
        name: "Standard Campus Laundry & Ironing (Per Bag)",
        category: "services",
        subcategory: "Laundry",
        startingPrice: 3500,
        priceType: "starting_from",
        priceLabel: "₦3,500 / 10kg Bag",
        providerId: "v-fresh-laundry",
        providerName: "FreshWash Campus Laundry",
        campus: "unimaid",
        turnaround: "24 Hours (Free Hostel Delivery)",
        image: "https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?w=600&auto=format&fit=crop&q=80",
        description: "Thorough machine wash with scented softener, crisp machine drying, and neatly folded or ironed clothes.",
        requiresPickupAddress: true,
        rating: 4.8
    },
    {
        id: "s-barbing-classic",
        name: "Executive Haircut & Beard Care Appointment",
        category: "services",
        subcategory: "Barbing",
        startingPrice: 1500,
        priceType: "fixed",
        priceLabel: "₦1,500 per session",
        providerId: "v-royale-cuts",
        providerName: "Royale Unisex Cuts & Salon",
        campus: "unimaid",
        turnaround: "Book Slot / In-Store",
        image: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=600&auto=format&fit=crop&q=80",
        description: "Sterilized equipment, custom fades, precision edging, beard trimming, aftershave, and scalp massage.",
        requiresAppointment: true,
        rating: 4.9
    },
    {
        id: "s-screen-repair",
        name: "Smartphone Screen & Battery Replacement",
        category: "services",
        subcategory: "Phone Repair",
        startingPrice: 5000,
        priceType: "quote",
        priceLabel: "Quote on Inspection (From ₦5,000)",
        providerId: "v-ifix-repairs",
        providerName: "iFix Tech & Phone Repairs",
        campus: "unimaid",
        turnaround: "2 - 4 Hours",
        image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80",
        description: "Original OEM replacement screens, battery testing, charging pin soldering, and water damage diagnostics.",
        requiresDeviceDetails: true,
        rating: 4.8
    },
    {
        id: "s-photography-portrait",
        name: "Graduation & Studio Portrait Photography",
        category: "services",
        subcategory: "Photography",
        startingPrice: 6000,
        priceType: "starting_from",
        priceLabel: "From ₦6,000 (5 Edited Photos)",
        providerId: "v-quickprint-press",
        providerName: "Studio One Campus Media",
        campus: "unimaid",
        turnaround: "24 - 48 Hours",
        image: "https://images.unsplash.com/photo-1554048612-b6a482bc67e5?w=600&auto=format&fit=crop&q=80",
        description: "High-resolution indoor/outdoor portrait sessions, convocation gown shoots, and professional retouching.",
        requiresAppointment: true,
        rating: 4.7
    }
];

export const MARKETPLACE_LISTINGS = [
    {
        id: "m-anatomy-textbook",
        title: "Clinical Anatomy by Regions (Richard Snell 10th Ed)",
        category: "marketplace",
        subcategory: "Used Textbooks",
        price: 6500,
        originalPrice: 18000,
        condition: "Good",
        sellerName: "Amina B. (500L Med)",
        sellerContact: "0803XXXXX12",
        campus: "unimaid",
        dateListed: "2 days ago",
        image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
        description: "Clean copy with minimal pencil notes in margin. Covers all neuroanatomy and thoracic regions. Perfect for 200L-400L students.",
        status: "Published",
        isModerated: true
    },
    {
        id: "m-mini-refrigerator",
        title: "ThermoCool Single Door 90L Hostel Mini Fridge",
        category: "marketplace",
        subcategory: "Used Electronics",
        price: 48000,
        originalPrice: 110000,
        condition: "Like New",
        sellerName: "Ibrahim K. (Finalist)",
        sellerContact: "0812XXXXX88",
        campus: "unimaid",
        dateListed: "Yesterday",
        image: "https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=600&auto=format&fit=crop&q=80",
        description: "Chills ice blocks in under 2 hours. Very quiet compressor and energy saving. Leaving campus after graduation.",
        status: "Published",
        isModerated: true
    },
    {
        id: "m-reading-table-chair",
        title: "Compact Wooden Study Desk & Cushioned Chair",
        category: "marketplace",
        subcategory: "Furniture",
        price: 14000,
        originalPrice: 32000,
        condition: "Good",
        sellerName: "Chinedu O. (Hostel C)",
        sellerContact: "0806XXXXX55",
        campus: "unimaid",
        dateListed: "3 days ago",
        image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600&auto=format&fit=crop&q=80",
        description: "Solid treated wood desk with book rack underneath and comfortable steel-frame chair.",
        status: "Published",
        isModerated: true
    },
    {
        id: "m-electric-kettle",
        title: "Stainless Steel 2.0L Rapid Boil Electric Kettle",
        category: "marketplace",
        subcategory: "Hostel Items",
        price: 4200,
        originalPrice: 9000,
        condition: "Fair",
        sellerName: "Fatima S. (Hostel E)",
        sellerContact: "0809XXXXX34",
        campus: "unimaid",
        dateListed: "4 days ago",
        image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600&auto=format&fit=crop&q=80",
        description: "Works 100%. Auto shut-off sensor intact. Upgraded to a multi-cooker so no longer needed.",
        status: "Published",
        isModerated: true
    }
];

export const INITIAL_ORDERS = [
    {
        id: "ORD-94821",
        type: "food",
        title: "Special Jollof Rice & Crispy Chicken + Zobo",
        vendor: "Safari Delight Kitchen",
        campus: "unimaid",
        itemsCount: 2,
        total: 2700,
        deliveryFee: 400,
        status: "Out for Delivery",
        statusStep: 4,
        date: "Today, 12:45 PM",
        fulfillment: "Delivery to Hostel C, Room 14"
    },
    {
        id: "SRV-48190",
        type: "service",
        title: "Final Year Project Printing & Binding (3 Copies)",
        vendor: "QuickPrint & Cyber Hub",
        campus: "unimaid",
        total: 4500,
        status: "Processing",
        statusStep: 3,
        date: "Yesterday, 03:10 PM",
        fulfillment: "Pickup at Library Annex"
    },
    {
        id: "DEL-20391",
        type: "delivery",
        title: "Campus Dispatch: Document Delivery from Senate to Law Faculty",
        vendor: "CLX Express Dispatch",
        campus: "unimaid",
        total: 600,
        status: "Delivered",
        statusStep: 5,
        date: "12 May 2026, 11:20 AM",
        fulfillment: "Delivered to Dept Office"
    }
];
