-- Phase 4F: resolve pgcrypto explicitly in the tracking RPC.
create or replace function public.get_customer_order_tracking(p_order_number text,p_tracking_token text) returns jsonb
language plpgsql security definer set search_path=pg_catalog,public,pg_temp as $$
declare o public.customer_orders%rowtype;
begin
 if length(trim(coalesce(p_order_number,'')))>32 or length(coalesce(p_tracking_token,'')) not between 32 and 256 then return jsonb_build_object('success',false,'code','ORDER_NOT_FOUND','message','Order tracking details were not found.'); end if;
 select co.* into o from public.customer_orders co where co.order_number=trim(p_order_number) and co.tracking_token_hash=extensions.crypt(p_tracking_token,co.tracking_token_hash); if not found then return jsonb_build_object('success',false,'code','ORDER_NOT_FOUND','message','Order tracking details were not found.'); end if;
 return jsonb_build_object('success',true,'order_number',o.order_number,'fulfillment_type',o.fulfillment_type,'status',o.status,'payment_status',coalesce((select p.status from public.customer_order_payments p where p.customer_order_id=o.id),'PENDING'::public.payment_status),'delivery_status',(select d.status from public.delivery_requests d where d.customer_order_id=o.id),'rider_name',(select r.name from public.delivery_requests d join public.riders r on r.id=d.rider_id where d.customer_order_id=o.id),'history',(select coalesce(jsonb_agg(jsonb_build_object('status',h.status,'created_at',h.created_at) order by h.created_at,h.id),'[]'::jsonb) from public.customer_order_status_history h where h.customer_order_id=o.id),'vendor_groups',(select coalesce(jsonb_agg(jsonb_build_object('vendor_name',g.vendor_name,'status',g.status,'items',g.items) order by g.vendor_name),'[]'::jsonb) from (select oi.vendor_name_snapshot vendor_name,ord.status,jsonb_agg(jsonb_build_object('product_name',oi.product_name_snapshot,'quantity',oi.quantity,'line_total_kobo',oi.total_price_kobo,'currency',oi.currency_code) order by oi.product_name_snapshot) items from public.orders ord join public.order_items oi on oi.order_id=ord.id where ord.customer_order_id=o.id group by ord.id,oi.vendor_name_snapshot,ord.status) g));
end $$;
